name: Deploy on Push or Manual Trigger

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22.5.1'

      - name: Setup SSH Key and Config
        env:
          SSH_KEY: ${{ secrets.SERVER_SSH_KEY }}   # Your private key
          SSH_HOST: ${{ secrets.SERVER_HOST }}       # Your server's host
          SSH_USER: ${{ secrets.SERVER_USERNAME }}    # Your SSH username
        run: |
          echo "Creating .ssh directory..."
          mkdir -p $HOME/.ssh/
          
          echo "Writing SSH key to staging.key..."
          echo "$SSH_KEY" > $HOME/.ssh/staging.key
          chmod 600 $HOME/.ssh/staging.key  # Set permissions for the private key
          
          echo "Creating SSH config file..."
          cat >> $HOME/.ssh/config <<EOF
          Host staging
              HostName $SSH_HOST
              User $SSH_USER
              IdentityFile $HOME/.ssh/staging.key
              StrictHostKeyChecking no
          EOF

      - name: Copy .env from Server
        run: |
          ssh staging "cat ~/labguy-server/.env" > .env

      - name: Load environment variables
        run: |
          set -a
          source .env
          set +a

      - name: Install dependencies
        run: npm install

      - name: Build the application
        run: npm run build

      - name: Deploy to Server
        if: ${{ success() }}
        run: |
          ssh staging << 'EOF'
            cd /path/to/your/app
            git pull origin main
            npm install
            npm run build
            pm2 restart <app_name>
EOF
