name: Deploy on Push or Manual Trigger

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22.5.1'

      - name: Print Debug Information
        run: |
          echo "Current User: $(whoami)"
          echo "Current Directory: $(pwd)"
          echo "Home Directory: $HOME"

      - name: Create SSH Key
        env:
          KEY: ${{ secrets.SERVER_SSH_KEY }}
        run: |
          echo "Creating .ssh directory..."
          mkdir -p $HOME/.ssh/
          
          echo "Writing SSH key to id_rsa..."
          echo "$KEY" > $HOME/.ssh/id_rsa
          
          echo "Checking contents of id_rsa..."
          cat $HOME/.ssh/id_rsa # This will show the key, check it looks okay

          echo "Setting permissions for id_rsa..."
          chmod 600 $HOME/.ssh/id_rsa

          echo "Adding host to known_hosts..."
          ssh-keyscan -H ${{ secrets.SERVER_HOST }} >> $HOME/.ssh/known_hosts
          
          echo "Finished creating SSH key setup."

      - name: Copy .env from Server
        env:
          HOST: ${{ secrets.SERVER_HOST }}
          USERNAME: ${{ secrets.SERVER_USERNAME }}
          PORT: ${{ secrets.SERVER_PORT }}
        run: |
          echo "Copying .env from server..."
          scp -P $PORT $USERNAME@$HOST:~/labguy-server/.env .env
          echo ".env file copied."

      - name: Verify .env file
        run: |
          echo "Verifying .env file..."
          ls -la .env
          cat .env

      - name: Load environment variables
        run: |
          echo "Loading environment variables..."
          set -a
          source .env
          set +a

      - name: Install dependencies
        run: npm install

      - name: Build the application
        run: npm run build

      - name: Deploy to Server
        if: ${{ success() }}
        env:
          HOST: ${{ secrets.SERVER_HOST }}
          USERNAME: ${{ secrets.SERVER_USERNAME }}
          PORT: ${{ secrets.SERVER_PORT }}
        run: |
          echo "Deploying to server..."
          ssh -p $PORT $USERNAME@$HOST << 'EOF'
            cd ~/labguy-server || { echo "Directory not found"; exit 1; }
            git pull origin main
            npm install
            npm run build
            pm2 restart <app_name> # Replace <app_name> with your actual app name
          EOF
