name: Deploy on Push or Manual Trigger

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22.5.1'

      - name: Print Debug Information
        run: |
          echo "Current User: $(whoami)"
          echo "Current Directory: $(pwd)"
          echo "Home Directory: $HOME"

      - name: Create SSH Key
        env:
          KEY: ${{ secrets.SERVER_SSH_KEY }}
        run: |
          # Ensure the .ssh directory exists
          mkdir -p $HOME/.ssh/
          # Write the key to id_rsa
          echo "$KEY" > $HOME/.ssh/id_rsa
          # Set appropriate permissions
          chmod 600 $HOME/.ssh/id_rsa
          # Add the server to known hosts
          ssh-keyscan -H ${{ secrets.SERVER_HOST }} >> $HOME/.ssh/known_hosts

      - name: Copy .env from Server
        env:
          HOST: ${{ secrets.SERVER_HOST }}
          USERNAME: ${{ secrets.SERVER_USERNAME }}
          PORT: ${{ secrets.SERVER_PORT }}
        run: |
          # Use the newly created SSH key to copy the .env file from the server
          scp -P $PORT $USERNAME@$HOST:~/labguy-server/.env .env

      - name: Verify .env file
        run: |
          # Check if the .env file has been copied correctly
          ls -la .env
          cat .env

      - name: Load environment variables
        run: |
          set -a
          source .env
          set +a

      - name: Install dependencies
        run: npm install

      - name: Build the application
        run: npm run build

      - name: Deploy to Server
        if: ${{ success() }}
        env:
          HOST: ${{ secrets.SERVER_HOST }}
          USERNAME: ${{ secrets.SERVER_USERNAME }}
          PORT: ${{ secrets.SERVER_PORT }}
        run: |
          # Deploy to the server using the created SSH key
          ssh -p $PORT $USERNAME@$HOST << 'EOF'
            cd ~/labguy-server || { echo "Directory not found"; exit 1; }
            git pull origin main
            npm install
            npm run build
            pm2 restart <app_name> # Replace <app_name> with your actual app name
          EOF
