name: Deploy on Push or Manual Trigger

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22.5.1'

      - name: Copy .env from Server
        env:
          HOST: ${{ secrets.SERVER_HOST }}
          USERNAME: ${{ secrets.SERVER_USERNAME }}
          PORT: ${{ secrets.SERVER_PORT }}
          KEY: ${{ secrets.SERVER_SSH_KEY }}
        run: |
          scp -i $KEY -P $PORT $USERNAME@$HOST:/labguy-server/ .env

      - name: Load environment variables
        run: |
          set -a
          source .env
          set +a

      - name: Install dependencies
        run: npm install

      - name: Build the application
        run: npm run build

      - name: Deploy to Server
        if: ${{ success() }}
        env:
          HOST: ${{ secrets.SERVER_HOST }}
          USERNAME: ${{ secrets.SERVER_USERNAME }}
          PORT: ${{ secrets.SERVER_PORT }}
          KEY: ${{ secrets.SERVER_SSH_KEY }}
        run: |
          ssh -i $KEY -o StrictHostKeyChecking=no -p $PORT $USERNAME@$HOST << 'EOF'
            cd /path/to/your/app
            git pull origin main
            npm install
            npm run build
            pm2 restart <app_name>
          EOF
